# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 260d27880e03c73dfb45dbc6a0dd879530743718bfae8acb2e82ca271b37953d08b78be64e01648505940c7e19576a8d7a39930a45aa4bc39bbe8a58153fc6f2

test:
  secret_key_base: 7b0ddcced3c399d95df6158d767dbd3ab19641d1d1d935dbba9ca9a5b92798162f1ef4aa27247b1017c2e8ed31401d9460348493c2e9e50deb68e74e46b48db7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
